version: '3'

services:
      backend:
          build: ./Backend
          ports: 
            - "4000:4000"
          volumes: 
               - ./Backend:/usr/src/app
          environment: 
                NODE_ENV: production
                 

      client:
          build: ./client
          ports: 
            - "3000:3000"  
          volumes:
            - ./client:/usr/src/app
         